version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./project/html:/var/www/html
      - ./project/nginx/conf:/etc/nginx
    env_file:
      - ./.env

  php:
    build: ./project/php
    container_name: php-container
    restart: always
    volumes:
      - ./project/html:/var/www/html
    expose:
      - 9000  
    env_file:
      - ./.env

  adjudicator:
    build: ./project/adjudicator
    command: python main.py run -h 0.0.0.0
    restart: always
    volumes:
      - ./project/adjudicator:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env


  database:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./.env

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./.env

volumes:
  db-data:
    name: "mysql-database"
