version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./project/html:/var/www/html
      - ./project/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./project/nginx/conf/conf.d:/etc/nginx/conf.d
      
  php:
    image: php:7.0-fpm
    container_name: php-container
    expose:
      - 9000 
    volumes:
      - ./project/html:/var/www/html